from __future__ import annotations

from datetime import date

from pydantic import BaseModel, Field, field_validator, model_validator


class Scenario(BaseModel):
    price: float = Field(..., gt=0, description="Projected JPY price at horizon")
    probability: float = Field(..., ge=0.0, le=1.0)
    rationale: str = Field(..., min_length=10, max_length=800)


class StockAnalysisResult(BaseModel):
    stock_code: str = Field(..., min_length=4, max_length=5)
    horizon_days: int = Field(..., gt=0, le=365)
    as_of: date
    last_close: float = Field(..., gt=0)
    summary: str = Field(..., min_length=20, max_length=2000)
    base: Scenario
    bull: Scenario
    bear: Scenario
    disclaimer: str = "Generated by an LLM. Not investment advice."

    @field_validator("stock_code")
    @classmethod
    def _digits_only(cls, v: str) -> str:
        v = v.strip()
        if not v.isdigit():
            raise ValueError("Japanese stock codes are numeric (e.g. 7203).")
        return v

    @model_validator(mode="after")
    def _probabilities_sum_to_one(self) -> "StockAnalysisResult":
        total = self.base.probability + self.bull.probability + self.bear.probability
        if abs(total - 1.0) > 0.02:
            raise ValueError(
                f"base/bull/bear probabilities must sum to ~1.0 (got {total:.3f})"
            )
        if not (self.bear.price < self.base.price < self.bull.price):
            raise ValueError(
                "Expected bear.price < base.price < bull.price"
            )
        return self
